#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motor2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	if(VexRT[BTN7L])
	{
			motor[motor1] = 127;
			motor[motor2] = 127;
	}
	else if (VexRT[BTN7R])
	{
		motor[motor1] = -127;
		motor[motor2] = -127;
	}
	else
	{
		motor[motor1] = 0;
		motor[motor2] = 0;
	}


}
