#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftMotor2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           middleMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftArmMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightArmMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor2,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// global config
short armUpSpeed = 64;
short armDownSpeed = -64;
short clawSpeed = 32;

task main()
{
	while (true)
	{
		//motor[port1] = vexRT[Ch1];
		//motor[port2] = vexRT[Ch1];

		motor[leftMotor] = vexRT[Ch2];
		motor[leftMotor2] = vexRT[Ch2];

		motor[rightMotor] = vexRT[Ch3];
		motor[rightMotor2] = vexRT[Ch3];

		motor[middleMotor] = (vexRT[Ch4] + vexRT[Ch1])/2;

		if(vexRT[Btn5D] == 1)
		{
			motor[leftArmMotor] = armDownSpeed;
			motor[rightArmMotor] = armDownSpeed;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[leftArmMotor] = armUpSpeed;
			motor[rightArmMotor] = armUpSpeed;
		}
		else
		{
			motor[leftArmMotor] = 0;
			motor[rightArmMotor] = 0;
		}

		if(vexRT[Btn6U])
		{
			motor[clawMotor] = clawSpeed;
			motor[clawMotor2] = -clawSpeed;
		}
		else if(vexRT[Btn6D])
		{
			motor[clawMotor2] = clawSpeed;
			motor[clawMotor] = -clawSpeed;
		}
		else
		{
			motor[clawMotor] = 0;
			motor[clawMotor2] = 0;
		}
	}
}
