#pragma config(Sensor, dgtl1,  ArmEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           ClawL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LiftLD,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LiftRD,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DriveL1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           DriveL2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           DriveL3,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           DriveR1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           DriveR2,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           DriveR3,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          ClawR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))

// autonomous helpers
void ZeroDrive()
{
	int power = 0;
	// Left
	motor[DriveL1] = power;
	motor[DriveL2] = power;
	motor[DriveL3] = power;

	//Right
	motor[DriveR1] = power;
	motor[DriveR2] = power;
	motor[DriveR3] = power;
}

void ZeroClaw()
{
	int power = 0;

	motor[ClawL] = power;
	motor[ClawR] = power;
}

void ZeroArm()
{
	int power = 0;

	motor[LiftLD] = power;
	motor[LiftRD] = power;
}

void MoveForward(int time)
{
	int power = 127;
	// Left
	motor[DriveL1] = power;
	motor[DriveL2] = power;
	motor[DriveL3] = power;

	//Right
	motor[DriveR1] = power;
	motor[DriveR2] = power;
	motor[DriveR3] = power;

	sleep(time);

	ZeroDrive();
}

void MoveForward()
{
	int power = 127;
	// Left
	motor[DriveL1] = power;
	motor[DriveL2] = power;
	motor[DriveL3] = power;

	//Right
	motor[DriveR1] = power;
	motor[DriveR2] = power;
	motor[DriveR3] = power;
}

void MoveBackwards(int time)
{
	int power = 127;
	// Left
	motor[DriveL1] = -power;
	motor[DriveL2] = -power;
	motor[DriveL3] = -power;

	//Right
	motor[DriveR1] = -power;
	motor[DriveR2] = -power;
	motor[DriveR3] = -power;

	sleep(time);

	ZeroDrive();
}

void MoveBackwards()
{
	int power = 127;
	// Left
	motor[DriveL1] = -power;
	motor[DriveL2] = -power;
	motor[DriveL3] = -power;

	//Right
	motor[DriveR1] = -power;
	motor[DriveR2] = -power;
	motor[DriveR3] = -power;
}

void TurnLeft(int time)
{
	int power = 127;
	// Left
	motor[DriveL1] = -power;
	motor[DriveL2] = -power;
	motor[DriveL3] = -power;

	//Right
	motor[DriveR1] = power;
	motor[DriveR2] = power;
	motor[DriveR3] = power;

	sleep(time);

	ZeroDrive();
}

void TurnLeft()
{
	int power = 127;
	// Left
	motor[DriveL1] = -power;
	motor[DriveL2] = -power;
	motor[DriveL3] = -power;

	//Right
	motor[DriveR1] = power;
	motor[DriveR2] = power;
	motor[DriveR3] = power;
}

void TurnRight(int time)
{
	int power = 127;
	// Left
	motor[DriveL1] = power;
	motor[DriveL2] = power;
	motor[DriveL3] = power;

	//Right
	motor[DriveR1] = -power;
	motor[DriveR2] = -power;
	motor[DriveR3] = -power;

	sleep(time);

	ZeroDrive();
}

void TurnRight()
{
	int power = 127;
	// Left
	motor[DriveL1] = power;
	motor[DriveL2] = power;
	motor[DriveL3] = power;

	//Right
	motor[DriveR1] = -power;
	motor[DriveR2] = -power;
	motor[DriveR3] = -power;
}

void ClawOpen(int time)
{
	int power = 60;

	motor[ClawL] = -power;
	motor[ClawR] = -power;

	sleep(time);

	ZeroClaw();
}

void ClawOpen()
{
	int power = 60;

	motor[ClawL] = -power;
	motor[ClawR] = -power;
}

void ClawClose(int time)
{
	int power = 60;

	motor[ClawL] = power;
	motor[ClawR] = power;

	sleep(time);

	ZeroClaw();
}

void ClawClose()
{
	int power = 60;

	motor[ClawL] = power;
	motor[ClawR] = power;
}

void ArmUp(int time)
{
	int power = 127;

	motor[LiftLD] = power;
	motor[LiftRD] = power;

	sleep(time);
	ZeroArm();
}

void ArmUp()
{
	int power = 127;

	motor[LiftLD] = power;
	motor[LiftRD] = power;
}

void ArmDown(int time)
{
	int power = 127;

	motor[LiftLD] = -power;
	motor[LiftRD] = -power;

	sleep(time);
	ZeroArm();
}

void ArmDown()
{
	int power = 127;

	motor[LiftLD] = -power;
	motor[LiftRD] = -power;
}

void StartClaw()
{
	// you should run this to setup the claw for autnomous
	motor(ClawL) = 127;
	motor(ClawR) = 127;
	sleep(20);
	motor(ClawL) = -127;
	motor(ClawR) = -127;
	sleep(20);
	motor(ClawL) = 127;
	motor(ClawR) = 127;
	sleep(650);
	ZeroClaw();
	sleep(50);
	ClawOpen();
	sleep(400);
	ZeroClaw();
}
void amazingDriverSkills()
{
	StartClaw();
	MoveBackwards();
	sleep(250);
	int i = 0;
	for(i=0; i<3; i++)
	{
		ZeroDrive();
		sleep(3000);
		ClawClose();
		sleep(1000);
		ArmUp();
		sleep(600);
		MoveBackwards();
		sleep(900);
		ZeroDrive();
		ZeroArm();
		ClawOpen();
		sleep(100);
		ZeroClaw();
		ArmDown();
		sleep(1400);
		ZeroArm();
		MoveForward();
		sleep(600);
	}
	ZeroDrive();
	sleep(500);
	ClawOpen();
	TurnLeft();
	sleep(50);
	ZeroClaw();
	sleep(180);
	ZeroDrive();
	ClawClose();
	sleep(600);
	MoveForward();
	sleep(500);
	TurnRight();
	ArmUp();
	sleep(500);

	MoveBackwards();

	ArmUp();


	sleep(1000);

	ZeroDrive();
	ZeroArm();

	ClawOpen();
	sleep(50);
	ZeroClaw();
}
void AutonomousCubeLeft()
{

	StartClaw();

	ArmDown();
	sleep(200);
	ZeroArm();
	MoveForward(850);
	ClawClose();
	sleep(1000);

	TurnRight();
	ArmUp();
	sleep(500);

	MoveBackwards();

	ArmUp();


	sleep(1000);

	ZeroDrive();
	ZeroArm();

	ClawOpen();
	sleep(50);
	ZeroClaw();

}

void AutonomousCubeRight()
{
  StartClaw();

	ArmDown();
	sleep(200);
	ZeroArm();

	MoveForward(850);

	ClawClose();
	sleep(1000);

	TurnLeft();

	ArmUp();
	sleep(500);


	MoveBackwards();

	ArmUp();


	sleep(1000);

	ZeroDrive();

	ZeroArm();

	ClawOpen();
	sleep(50);

	ZeroClaw();
}

void AutonomousGeneric()
{
	StartClaw();
	sleep(200);
	ClawClose();
	sleep(50);
	ZeroClaw();
	ArmUp();
	MoveForward();
	sleep(600);
	ZeroArm();
	ZeroDrive();
}



// for movement
// 500 is 30 inches (including drifting) 1 square

// for turning
// 100 is 90/4
// 250 is 90

typedef enum k_autonomous_debug
{
	AUTONOMOUS_TURN_RIGHT = 0,
	AUTONOMOUS_TURN_LEFT,
	AUTONOMOUS_FORWARD,
	AUTONOMOUS_BACKWARD,
	AUTONOMOUS_ARM_UP,
	AUTONOMOUS_ARM_DOWN,
	AUTONOMOUS_CLAW_OPEN,
	AUTONOMOUS_CLAW_CLOSE,
	AUTONOMOUS_DEBUG_LAST,
} autonomous_debug_t;

string autonomous_debug_strings[] =
{
	"TURN_RIGHT",
	"TURN_LEFT",
	"FORWARD",
	"BACKWARD",
	"ARM_UP",
	"ARM_DOWN",
	"CLAW_OPEN",
	"CLAW_CLOSE"
};


// ============================================================
// COMPETITION AUTONOMOUS
// ============================================================

// TODO: Fix this - cube left mode and fix the menu system to use correct types

typedef enum k_autonomous_mode
{
	AUTONOMOUS_GENERIC = 0,
	AUTONOMOUS_CUBE_RIGHT,
	AUTONOMOUS_CUBE_LEFT,
	AUTONOMOUS_DEBUG,
	AMAZING_PROG,
	AUTONOMOUS_MODE_LAST,
} autonomous_mode_t;

string autonomous_mode_strings[] =
{
	"generic",
	"cube right",
	"cube left",
	"debug",
	"prog skill",
};

// global for the autonomous mode selected
// the default autonomous mode is generic
// TODO: change this if we need to
autonomous_mode_t g_autonomous_mode = AUTONOMOUS_GENERIC;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = false;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = false;

  bLCDBacklight = true;

  int buttonsPressed = 0;

 	bool buttonsEqual = 0;

	int time;

	while(true)
	{
		sleep(100);
		buttonsPressed = nLCDButtons;

		// right button cycles through modes
		// center button selects them
		// debug mode is its own autonomous mode
		if(buttonsPressed == 4)
		{
			g_autonomous_mode = (g_autonomous_mode + 1) % AUTONOMOUS_MODE_LAST;
		}
		else if(buttonsPressed == 2)
		{
			// when the button is pressed twice in a row it is selected
			clearLCDLine(0);
			displayLCDString(0, 0, autonomous_mode_strings[g_autonomous_mode]);
			clearLCDLine(1);
			displayLCDString(0, 0, "selected");
			break;
		}

		// display the currently selected mode from the list
		clearLCDLine(0);
		displayLCDString(0, 0, autonomous_mode_strings[g_autonomous_mode]);

		clearLCDLine(1);
		displayLCDString(1, 0, "Press center to select...");
	}
}

task autonomous()
{
	if(g_autonomous_mode == AUTONOMOUS_GENERIC)
	{
		AutonomousGeneric();
	}
	else if(g_autonomous_mode == AUTONOMOUS_CUBE_LEFT)
	{
		AutonomousCubeLeft();
	}
	else if(g_autonomous_mode == AUTONOMOUS_CUBE_RIGHT)
	{
		AutonomousCubeRight();
	}
	else if(g_autonomous_mode == AMAZING_PROG)
	{
		amazingDriverSkills();
	}
	else if(g_autonomous_mode == AUTONOMOUS_DEBUG)
	{
		int buttonsPressed = 0;

		int time;

		autonomous_debug_t mode;

		while(true)
		{

			do
			{
				sleep(100);
				buttonsPressed = nLCDButtons;

				if(buttonsPressed == 5)
				{
					mode = (mode + 1) % AUTONOMOUS_DEBUG_LAST;
				}
				else if(buttonsPressed == 1)
				{
					time -= 10;
				}
				else if(buttonsPressed == 4)
				{
					time += 10;
				}

				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDString(0, 0, autonomous_debug_strings[mode]);
				displayLCDNumber(1, 0, time);
			}
			while(buttonsPressed != 2);

			if(mode == AUTONOMOUS_TURN_RIGHT)
			{
				TurnRight(time);
			}
			else if(mode == AUTONOMOUS_TURN_LEFT)
			{
				TurnLeft(time);
			}
			else if(mode == AUTONOMOUS_FORWARD)
			{
				MoveForward(time);
			}
			else if(mode == AUTONOMOUS_BACKWARD)
			{
				MoveBackwards(time);
			}
			else if(mode == AUTONOMOUS_ARM_UP)
			{
				ArmUp(time);
			}
			else if(mode == AUTONOMOUS_ARM_DOWN)
			{
				ArmDown(time);
			}
			//these two are inverted for some reason.... ? -Sam
			else if(mode == AUTONOMOUS_CLAW_OPEN)
			{
				ClawClose(time);
			}
			else if(mode == AUTONOMOUS_CLAW_CLOSE)
			{
				ClawOpen(time);
			}
		}
	}
}

task usercontrol()
{
  // User control code here, inside the loop
  bool closeSwitch = false;
	int toggle = 1;
	int clawTick = 0;

	//int encoderAcc = 0;

  //Clear Encoders
  SensorValue[ArmEncoder] = 0;

  string mainBattery, backupBattery;

  while (true)
  {
  	if (vexRT[Btn7L])
  	{
  		// clear the lcd display
	  	clearLCDLine(0);
			clearLCDLine(1);

			// Display the Primary Robot battery voltage
			displayLCDString(0, 0, "Primary: ");
			sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
			displayNextLCDString(mainBattery);

			// Display the Backup battery voltage
			displayLCDString(1, 0, "Backup: ");
			sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
			displayNextLCDString(backupBattery);

			// Short delay for the LCD refresh rate
			// do we really want to be doing this? this will block this thread -
			// resulting in us being unable to use the robot for this time period
			wait1Msec(100);
		}

  	//sprintf(lcdDisplay, "%f", SensorValue[ArmEncoder]);
    //encoderAcc += SensorValue[ArmEncoder];
    displayLCDNumber(0, 0, SensorValue[ArmEncoder]);
    //SensorValue[ArmEncoder] = 0;

    int l = (vexRT[Ch3] + vexRT[Ch1]);
		int r = (vexRT[Ch3] - vexRT[Ch1]);

		float flForward = vexRT[Ch3];
		float flSide = vexRT[Ch1];

		int clawSpeed = 127;
		//Left
		motor[DriveL1] = l;
		motor[DriveL2] = l;
		motor[DriveL3] = l;
		//Right
		motor[DriveR1] = r;
		motor[DriveR2] = r;
		motor[DriveR3] = r;
		//Arm
		if (vexRT[Btn5U]) //Up
		{
			motor[LiftRD] = 127;
			motor[LiftLD] = 127;
		}
		else if (vexRT[Btn5D]) //Down
		{
			motor[LiftRD] = -127;
			motor[LiftLD] = -127;
		}
		else //Stop
		{
			motor[LiftRD] = 0;
			motor[LiftLD] = 0;
		}
		//Claw
		if (vexRT[Btn6U]) // Close
		{
			if(clawTick > 1000)
			{
				clawSpeed -= MIN(50, clawTick);
			}
			motor[ClawR] = clawSpeed;
			motor[ClawL] = clawSpeed;
			closeSwitch = false;
			clawTick += 1;

		}
		else if (vexRT[Btn6D]) // Open
		{
			if(clawTick > 1000)
			{
				clawSpeed -= MIN(50, clawTick);
			}
			motor[ClawR] = -clawSpeed;
			motor[ClawL] = -clawSpeed;
			//closeSwitch = true;
			clawTick += 1;

		}
		else //Stop
		{
			clawTick = 0;
			if (closeSwitch == false)
			{
				motor[ClawR] = 0;
				motor[ClawL] = 0;
			}

		if (vexRT(Btn7U))
		{
			motor[ClawR] = -127;
			motor[ClawL] = -127;
		}
			/*else
			{
				motor[ClawR] = -60;
				motor[ClawL] = -60;
			}
			*/
		}
  }
}
