#pragma config(Motor,  port1,           motorLEFT,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorCENTRE,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           motorLARM,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motorRARM,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          motorRIGHT,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{




	while(true)
	{


		motor[motorLEFT] = vexRT[Ch3];
		motor[motorRIGHT] = vexRT[Ch2];
		motor[motorCENTRE] = vexRT[Ch1];

		//Down
		if(vexRT[Btn6U] == 1)
		{
			motor[motorRARM] = 127;
			motor[motorLARM] = 127;
		}
		//Lift Up
		else if(vexRT[Btn6D] == 1)
		{
			motor[motorRARM] = -127;
			motor[motorLARM] = -127;
		}
		//Autonomous Code
		else if(vexRT[Btn7L])
		{
			motor(motorRARM) = -127;
			motor(motorLARM) = -127;
			sleep(5000);
			motor(motorRARM) = 127;
			motor(motorLARM) = 127;
			motor(motorLEFT) = 127;
			motor(motorRIGHT) = 127;
			sleep(2000);
			motor(motorLEFT) = 0;
			motor(motorRIGHT) = 0;
			motor(motorCENTRE) = 127;
			sleep(3000);
			motor(motorCENTRE) = -127;
			sleep(3500);
			motor(motorCENTRE) = 127;
			sleep(750);
			motor(motorCENTRE) = 0;
			motor(motorRARM) = 0;
			motor(motorLARM) = 0;
		}
		//Do nothing
		else
		{
			motor[motorRARM] = 0;
			motor[motorLARM] = 0;
		}









	}
}
