#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motor2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (vexRT[Btn8U])
		{
			motor[motor1] = 127;
			motor[motor2] = 127;
		}
		else if (vexRT[Btn8D])
		{
			motor[motor1] = -127;
			motor[motor2] = -127;
		}
		else
		{
			motor[motor1] = 0;
			motor[motor2] = 0;
		}
	}

}
