#ifdef ROBOT_ROBBIE
#pragma config(Sensor, dgtl2,  encoder_drive_left, sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  encoder_drive_right, sensorQuadEncoder)
#pragma config(Motor,  port1,           drive_left_back, tmotorNone, openLoop)
#pragma config(Motor,  port2,           drive_left_front, tmotorNone, openLoop)
#pragma config(Motor,  port3,           drive_spinner, tmotorNone, openLoop)
#pragma config(Motor,  port9,           drive_right_front, tmotorNone, openLoop)
#pragma config(Motor,  port10,          drive_right_back, tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#else

#endif
