#pragma config(Motor,  port1,           CL,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LL1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LL2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LR1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LR2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           DR2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          CR,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true) {
    	//Drive
				int l = (vexRT[Ch3] + vexRT[Ch1]);
        int r = (vexRT[Ch3] - vexRT[Ch1]);
        //Left
        motor[DL1] = l;
        motor[DL2] = l;
        //Right
        motor[DR1] = r;
        motor[DR2] = r;
		//Lift
        //Up
        if (vexRT[Btn5D]) {
            motor[LL1] = 127;
            motor[LL2] = 127;
            motor[LR1] = 127;
            motor[LR2] = 127;
       }
       //Down
        else if (vexRT[Btn6D]) {
            motor[LL1] = -127;
            motor[LL2] = -127;
            motor[LR1] = -127;
            motor[LR2] = -127;
        }
        else {
            motor[LL1] = 0;
            motor[LL2] = 0;
            motor[LR1] = 0;
            motor[LR2] = 0;
        }
        //Claw
        //Open
        if (vexRT[Btn6U]) {
            motor[CL] = 60;
            motor[CR] = 60;
       	}
       	//Close
        else if (vexRT[Btn5U]) {
            motor[CL] = -60;
            motor[CR] = -60;
        }
        else {
            motor[CL] = 0;
            motor[CR] = 0;
    	}
	}
}
