#pragma config(Motor,  port4,           RL1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RL2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LL2,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true){
	motor[RL1] = vexRT[Ch2];
	motor[RL2] = vexRT[Ch2];
	motor[LL1] = vexRT[Ch2];
	motor[LL2] = vexRT[Ch2];

}


}
