#pragma config(Motor,  port4,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           R2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           R3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           L3,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true){
	motor[R1] = vexRT[Ch2];
	motor[R2] = vexRT[Ch2];
	motor[R3] = vexRT[Ch2];
	motor[L1] = vexRT[Ch3];
	motor[L2] = vexRT[Ch3];
	motor[L3] = vexRT[Ch3];
}


}
