#pragma config(Sensor, in7,    lineSensor,     sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		float sensorVar = SensorValue[lineSensor];
		writeDebugStreamLine("val: %f", sensorVar);

	}
}
