#pragma config(Motor,  port1,           motor,         tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor[port1] = vexRT[Ch1];
	}
}
